services:
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel
        build:
            context: .
            dockerfile: Dockerfile
        command: >
            sh -c "
              php artisan config:clear &&
              php artisan migrate --force &&
              php artisan serve --host=0.0.0.0 --port=8000
            "

    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
